### ISSUE TITLE
Empty tarball on CPAN

### ISSUE THREAD

**Issue by eserte** [njlg/perl-rethinkdb#13]
NJLG/Rethinkdb-0.08.tar.gz on CPAN is mostly empty (just the META files are there).

**Comment by njlg** [comment]
Yeah. I didn't realize I packaged it wrong until after I uploaded it. I scheduled it for remove all (but it takes a couple days). I hope to be uploading 0.09 today and then will backfill 0.08 as soon as I can.

**Comment by njlg** [comment]
Here's the new version: https://metacpan.org/release/NJLG/Rethinkdb-0.09
I'm not sure how long it takes to propagate out.

**Comment by eserte** [comment]
Looks fine now.
