### ISSUE TITLE
Large record fails to get all data past 1428 bytes

### ISSUE THREAD

**Issue by grantwork** [njlg/perl-rethinkdb#19]
I have some records that have Base64 images which are around 130k.

Running a get on one of these records fails with the below error.

> unexpected end of string while parsing JSON string, at character offset 1428 (before "(end of string)") at _config/lib/share/Rethinkdb/IO.pm line 206

I tinkered with IO.pm to try debug the error and it looks like it just doesn't receive the full data from the 'recv' command on line 297. When I print $length it returns the correct size (around 130k in my case), but this command only outputs 1428 bytes of data.

```perl
  $self->_handle->recv( $data, $length );
```

**Comment by njlg** [comment]
I just noticed this too. I have a fix for it that I can push soon. Thanks for reporting the issue.

**Comment by njlg** [comment]
This should be resolved in the latest version (0.11).

**Comment by grantwork** [comment]
Looks to be working fine now. Thanks.
