### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by BlueT** [njlg/perl-rethinkdb#2]
cpanm (App::cpanminus) 1.5018 on perl 5.016003 built for x86_64-linux
Work directory is /home/matthew/.cpanm/work/1384355024.24530
You have make /usr/bin/make
You have LWP 6.05
You have /bin/tar: tar (GNU tar) 1.26
Copyright © 2011 Free Software Foundation, Inc.
使用授權 GPLv3+: GNU GPL 第三版或後續版本<http://gnu.org/licenses/gpl.html>。
這是自由軟體：您可以自由變更和再次散布它。
在法律所允許的範圍內沒有任何擔保。

由 John Gilmore 和 Jay Fenlason 編寫。
You have /usr/bin/unzip
--> Working on .
Entering /home/matthew/workspace/perl-rethinkdb
Configuring /home/matthew/workspace/perl-rethinkdb
Running Makefile.PL
Generating a Unix-style Makefile
Writing Makefile for Rethinkdb
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.82)
Checking if you have Carp::Always 0 ... Yes (0.13)
Checking if you have Google::ProtocolBuffers 0.08 ... Yes (0.09)
Building and testing Rethinkdb-0.03
Skip blib/lib/Rethinkdb.pm (unchanged)
Skip blib/lib/Rethinkdb/Table.pm (unchanged)
Skip blib/lib/Rethinkdb/Protocol.pm (unchanged)
Skip blib/lib/Rethinkdb/Query.pm (unchanged)
Skip blib/lib/Rethinkdb/Query/Datum.pm (unchanged)
Skip blib/lib/Rethinkdb/Base.pm (unchanged)
Skip blib/lib/Rethinkdb/Response.pm (unchanged)
Skip blib/lib/Rethinkdb/IO.pm (unchanged)
Skip blib/lib/Rethinkdb/Util.pm (unchanged)
Skip blib/lib/Rethinkdb/Database.pm (unchanged)
Manifying blib/man3/Rethinkdb::Base.3
PERL_DL_NONLAZY=1 /home/matthew/perl5/perlbrew/perls/perl-5.16.0/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t

#   Failed test 'Correct response'
#   at t/aggregation.t line 216.
#     Structures begin differing at:
#          $got->[1]{reduction}{superhero} = 'Ant-Man'
#     $expected->[1]{reduction}{superhero} = 'Wolverine'
# Looks like you failed 1 test of 14.
t/aggregation.t ...... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/14 subtests 
t/aggregators.t ...... ok
t/connect.t .......... ok
t/control.t .......... ok

#   Failed test 'Correct response'
#   at t/datetime.t line 130.
#          got: '7'
#     expected: '9'
# Looks like you failed 1 test of 45.
t/datetime.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/45 subtests 
t/db.t ............... ok
t/document.t ......... ok
t/joins.t ............ ok
t/logic.t ............ ok
t/pod.t .............. skipped: set TEST_POD to enable this test (developer only!)
t/pod_coverage.t ..... skipped: set TEST_POD to enable this test (developer only!)
t/selecting.t ........ ok
t/string.t ........... ok
t/table.t ............ ok

#   Failed test 'Correct number of documents'
#   at t/transformations.t line 160.
#     Structures begin differing at:
#          $got->[0] = '77'
#     $expected->[0] = '273'

#   Failed test 'Correct document fields'
#   at t/transformations.t line 182.
#     Structures begin differing at:
#          $got->[0] = 'Werebear'
#     $expected->[0] = 'Werecat'

#   Failed test 'Correct order'
#   at t/transformations.t line 219.
#     Structures begin differing at:
#          $got->[0] = 'Wasp'
#     $expected->[0] = 'Spider-Man'

#   Failed test 'Correct order'
#   at t/transformations.t line 226.
#     Structures begin differing at:
#          $got->[0] = 'Ant-Man'
#     $expected->[0] = 'Captain America'

#   Failed test 'Correct response'
#   at t/transformations.t line 233.
#          got: 'Hulk'
#     expected: 'Wasp'
# Looks like you failed 5 tests of 31.
t/transformations.t .. 
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/31 subtests 
t/writing.t .......... ok

Test Summary Report
-------------------
t/aggregation.t    (Wstat: 256 Tests: 14 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
t/datetime.t       (Wstat: 256 Tests: 45 Failed: 1)
  Failed test:  10
  Non-zero exit status: 1
t/transformations.t (Wstat: 1280 Tests: 31 Failed: 5)
  Failed tests:  2, 8, 14-15, 17
  Non-zero exit status: 5
Files=16, Tests=360, 41 wallclock secs ( 0.11 usr  0.04 sys +  2.13 cusr  0.20 csys =  2.48 CPU)
Result: FAIL
Failed 3/16 test programs. 7/360 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing . failed. See /home/matthew/.cpanm/build.log for details.

**Comment by BlueT** [comment]
Failed in t/control.t , t/db.t and t/transformations.t

############
# for control.t
############

#   Failed test 'Correct response'
#   at t/control.t line 168.
#     Structures begin differing at:
#          $got->{db}{id} = '57bb6099-cc81-4c63-a578-bb8e975568c1'
#     $expected->{db}{id} = Does not exist
# Looks like you failed 1 test of 28.
t/control.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/28 subtests 

using data explorer with this query:
r.table('marvel').info()
 I got:

{
    "db": {
        "id": "e8360798-97f5-408c-9417-191697f4e5ee" ,
        "name": "test" ,
        "type": "DB"
    } ,
    "doc_count_estimates": [
        8
    ] ,
    "id": "a49f65ad-c4e8-4c45-9ca9-f84f6774b746" ,
    "indexes": [ ],
    "name": "marvel" ,
    "primary_key": "superhero" ,
    "type": "TABLE"
}

The test missing "id" for comparism.


##################
# db.t
##################
#   Failed test 'Correct document fields'
#   at t/transformations.t line 171.
#     Structures begin differing at:
#          $got->[0] = 'age'
#     $expected->[0] = 'superhero'
# Looks like you failed 1 test of 32.
t/transformations.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/32 subtests 

the response is
$res->response = [
                   'rethinkdb',
                   'superheroes'
                 ];
so the answer is 
is_deeply $res->response, ['rethinkdb','superheroes'], 'Db was created and listed';

**Comment by BlueT** [comment]
and this is due to hash key seq randomize

#   Failed test 'Correct document fields'
#   at t/transformations.t line 171.
#     Structures begin differing at:
#          $got->[0] = 'age'
#     $expected->[0] = 'superhero'
# Looks like you failed 1 test of 32.
t/transformations.t .. 


answer should be 
is_deeply [ sort keys %{ $res->response->[0] } ], [ 'age', 'superhero' ],

**Comment by BlueT** [comment]
there's still one fail in control.t, I think the bug haven't been fixed yet

**Comment by njlg** [comment]
Okay. I'll reopen. I've been meaning to hook this project up to Travis-CI so I can do more testing on other machines.

**Comment by njlg** [comment]
Are you still seeing this problem? I hooked this project up to Travis CI and the tests seem to pass there (now) https://travis-ci.org/njlg/perl-rethinkdb
