### ISSUE TITLE
Extraneous Errors

### ISSUE THREAD

**Issue by njlg** [njlg/perl-rethinkdb#28]
Lots of 
`Use of uninitialized value $length in string eq at /usr/local/share/perl/5.18.2/Rethinkdb/IO.pm line 345.`
in the error logs.

(reported by Rob Hartill)

**Comment by rob0101** [comment]
I haven't seen this for a while now.
Will report back if I encounter it again.
Version 2.3.2 btw.

**Comment by njlg** [comment]
I added a small little tweak that might help. If you notice anything just put in another issue.
